### ISSUE TITLE
build fails on GradleBuildSearchTest 

### ISSUE THREAD

**Issue by plutext** [centic9/github-version-statistics#1]
org.dstadler.github.GradleBuildSearchTest > parseVersionShortVar FAILED
    java.lang.IllegalStateException at GradleBuildSearchTest.java:80

org.dstadler.github.GradleBuildSearchTest > parseVersionLong FAILED
    java.lang.IllegalStateException at GradleBuildSearchTest.java:94

org.dstadler.github.GradleBuildSearchTest > parseVersionShort FAILED
    java.lang.IllegalStateException at GradleBuildSearchTest.java:73

**Comment by centic9** [comment]
This works for me locally and in TravisCI at https://travis-ci.org/centic9/github-version-statistics, can you provide details like the full details/stacktrace of the test-failures?

**Comment by plutext** [comment]
I know see that changing

```
    protected final static String GROUP_REGEX = "org\\.apache\\.poi";
    protected final static String GROUP = "org.apache.poi";
```

to

```
    protected final static String GROUP_REGEX = "org\\.foo";
    protected final static String GROUP = "org.foo";
```

is the cause of the test failures.
